### ISSUE TITLE
one more Strict Concurrency issue

### ISSUE THREAD

**Issue by thomasRademaker** [lukepistrol/TaskTrigger#3]
This time inside the `.task` modifier.
If you set the demo project's Strict Concurrency Checking to `Complete` this line
https://github.com/lukepistrol/TaskTrigger/blob/main/TaskTriggerDemo/TaskTriggerDemo/ContentView.swift#L81
has a warning
> Capture of 'self' with non-sendable type 'ContentView' in a `@Sendable` closure

How should this be handled?

**Comment by thomasRademaker** [comment]
Looking over it this might be something Apple needs to fix in SwiftUI. Curious your thoughts.

**Comment by lukepistrol** [comment]
I forgot one `@MainActor` declaration in the "plain" task modifiers closure.
