### ISSUE TITLE
trigger is firing twice?

### ISSUE THREAD

**Issue by thomasRademaker** [lukepistrol/TaskTrigger#5]
```swift
@State private var myTrigger = PlainTaskTrigger()

var body: some View {
    Text("hello")
      .onAppear { trigger() }
      .task($myTrigger) { await myMethod() }
}

func trigger() {
    myTrigger.trigger()
}

func myMethod() async {
    // Do async work
}
```

In this code sample, `trigger()` fires once, but `myMethod()` fires twice. 😢
Please advise. What am I doing wrong?

**Comment by lukepistrol** [comment]
@thomasRademaker any news on this topic? Are you able to link a sample project which reproduces said issue?

**Comment by thomasRademaker** [comment]
I'm seeing it in a pretty complex codebase. I will try to reproduce on something simpler that I can share. But it might not be an issue with this package. I'll update you sometime next week.

**Comment by thomasRademaker** [comment]
Sorry this took so long. I have some code to reproduce the issue.
Use the `task_trigger_bug` branch of this repo - https://github.com/SparrowTek/Boostz/tree/task_trigger_bug

The buggy task trigger is in `SyncConfigData` and I have added some print statements

Run the app and tap the "Alby" button. This will take you to the next view with the buggy task trigger. You will see the following print to the console,

### TRIGGER
### past guard
### TRIGGER
### GET DATA
### GET DATA

### Trigger being called twice isn't an issue because the task trigger isn't triggered until after ### past guard.

I hope the code makes sense. Let me know if you have any questions.

**Comment by smiLLe** [comment]
I think this is related to `onAppear` because I experience the same issue whenever I trigger an event in `onAppear`

**Comment by thomasRademaker** [comment]
That was my first thought, but I'm positive with my code the `PlainTaskTrigger` is only triggered once. So something in the task trigger logic is firing twice. But it isn't consistent every time I use a plain task trigger. It's a weird bug.

**Comment by thomasRademaker** [comment]
This is definitely a SwiftUI bug and not a bug with TaskTrigger. I am able to replicate with using the task modifier that takes an id parameter. I'll file a feedback with Apple.
